---
abstract: 'syslog services for POE'
author:
  - 'Matt Cashner (sungo@pobox.com)'
build_requires:
  ExtUtils::MakeMaker: 6.42
  Test::More: 0.47
configure_requires:
  ExtUtils::MakeMaker: 6.42
distribution_type: module
generated_by: 'Module::Install version 1.00'
license: bsd
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: POE-Component-Server-Syslog
no_index:
  directory:
    - examples
    - inc
    - t
provides:
  POE::Component::Server::Syslog:
    file: lib/POE/Component/Server/Syslog.pm
    version: 1.20
  POE::Component::Server::Syslog::TCP:
    file: lib/POE/Component/Server/Syslog/TCP.pm
    version: 1.20
  POE::Component::Server::Syslog::UDP:
    file: lib/POE/Component/Server/Syslog/UDP.pm
    version: 1.20
  POE::Filter::Syslog:
    file: lib/POE/Filter/Syslog.pm
    version: 1.20
requires:
  Carp: 0
  IO::Socket: 0
  IO::Socket::INET: 0
  POE: 0.24
  POE::Driver::SysRW: 0
  POE::Wheel::ReadWrite: 0
  POE::Wheel::SocketFactory: 0
  Params::Validate: 0
  Test::More: 0
  Time::ParseDate: 0
  perl: 5.6.1
resources:
  homepage: http://github.com/bingos/poe-component-server-syslog/tree
  license: http://opensource.org/licenses/bsd-license.php
  repository: git://github.com/bingos/poe-component-server-syslog.git
version: 1.20
