name: POE-Component-Server-Syslog
version: 1.03
author: Matt Cashner (sungo@pobox.com)
license: bsd
distribution_type: module
requires:
  POE: 0.24
  Params::Validate: 0
  IO::Socket: 0
  Time::ParseDate: 0
  Test::More: 0
  Carp: 0
no_index:
  directory:
    - inc
generated_by: Module::Install version 0.39
