#!/usr/bin/perl

use strict;
use warnings;

use IO::Socket::INET;

my $sock = IO::Socket::INET->new(
    PeerPort  => 9999,
    PeerAddr  => 'localhost',
    Proto     => 'udp',
    Broadcast => 1 )
or die "Can't bind : $@\n";

$sock->send("<1> sungo: pie");
